from pathlib import Path
from urllib.parse import quote
import re
root=Path(__file__).parent/'dist';origin='https://creamchargersdubai.com'
areas=[
('dubai-marina','Dubai Marina',
 'For cafés and dessert kitchens in Dubai Marina, a compact cylinder can be a practical choice for everyday cream whipping. Send your dispenser model and your expected usage so we can discuss the format before you order.',
 'Voor cafés en dessertkeukens in Dubai Marina kan een compacte cilinder praktisch zijn voor het dagelijks bereiden van slagroom. Stuur het model van je slagroomspuit en je verwachte gebruik, zodat we vóór je bestelling het formaat kunnen bespreken.',
 'Pour les cafés et cuisines de desserts à Dubai Marina, un cylindre compact peut être pratique pour la crème fouettée au quotidien. Envoyez le modèle de votre siphon et votre consommation prévue pour discuter du format avant de commander.'),
('downtown-dubai','Downtown Dubai',
 'Preparing plated desserts in Downtown Dubai? Tell us whether you need cream chargers for occasional finishing or regular service. We can discuss Smartwhip and Cream Deluxe options and confirm the cylinder variant through WhatsApp.',
 'Bereid je desserts op in Downtown Dubai? Vertel of je slagroompatronen nodig hebt voor af en toe afwerken of voor regelmatig gebruik. Via WhatsApp bespreken we Smartwhip en Cream Deluxe en bevestigen we de cilindervariant.',
 'Vous préparez des desserts à l’assiette à Downtown Dubai ? Indiquez si vous avez besoin de cartouches pour des finitions occasionnelles ou un service régulier. Sur WhatsApp, nous discutons des options Smartwhip et Cream Deluxe et confirmons le modèle.'),
('business-bay','Business Bay',
 'For a catering kitchen or hospitality business in Business Bay, repeat ordering starts with a clear product specification. Share the cylinder you currently use, your quantity and your delivery requirements to discuss a suitable reorder.',
 'Voor een cateringkeuken of horecabedrijf in Business Bay begint opnieuw bestellen met een duidelijke productspecificatie. Deel je huidige cilinder, het aantal en je bezorgwensen om een passende vervolgbestelling te bespreken.',
 'Pour une cuisine de traiteur ou un établissement à Business Bay, une commande régulière commence par une référence précise. Partagez votre cylindre actuel, la quantité et vos besoins de livraison pour préparer votre prochaine commande.'),
('jbr','JBR',
 'Cream whipping for your JBR kitchen should start with the right equipment match. Before placing an order, send a photo or model number of your dispenser and regulator, together with the product you want to discuss.',
 'Voor slagroom in je keuken in JBR begint de keuze met passende apparatuur. Stuur vóór je bestelling een foto of modelnummer van je slagroomspuit en regelaar, samen met het product dat je wilt bespreken.',
 'Pour la crème fouettée dans votre cuisine à JBR, commencez par vérifier le matériel compatible. Avant de commander, envoyez une photo ou la référence de votre siphon et de votre régulateur, ainsi que le produit souhaité.'),
('jumeirah','Jumeirah',
 'Whether you prepare pastries, cakes or light dessert foams in Jumeirah, explain how your kitchen uses cream chargers. We can discuss a compact or larger cylinder format and confirm fittings before the order is finalised.',
 'Maak je gebak, taarten of lichte dessertschuimen in Jumeirah? Vertel hoe je keuken slagroompatronen gebruikt. We bespreken een compact of groter cilinderformaat en bevestigen de aansluitingen vóór je definitieve bestelling.',
 'Vous préparez des pâtisseries, des gâteaux ou des mousses à Jumeirah ? Expliquez l’utilisation de vos cartouches. Nous pouvons discuter d’un cylindre compact ou plus grand et confirmer les raccords avant la commande.'),
('palm-jumeirah','Palm Jumeirah',
 'For a private chef, catering team or professional kitchen on Palm Jumeirah, include the delivery point and any building access instructions in your enquiry. Product availability, timing and the final total are confirmed before dispatch.',
 'Voor een privékok, cateringteam of professionele keuken op Palm Jumeirah: vermeld de bezorglocatie en eventuele toegangsinstructies in je aanvraag. Voorraad, bezorgtijd en totaalbedrag worden vóór verzending bevestigd.',
 'Pour un chef privé, un traiteur ou une cuisine professionnelle à Palm Jumeirah, précisez le point de livraison et les consignes d’accès. Le stock, le délai et le montant final sont confirmés avant l’expédition.'),
('al-barsha','Al Barsha',
 'Choosing cream chargers for your Al Barsha kitchen? Compare your expected usage with the available cylinder formats. Send the brand and variant you need, or ask us to help confirm the product before requesting a delivery quote.',
 'Kies je slagroompatronen voor je keuken in Al Barsha? Vergelijk je verwachte gebruik met de beschikbare cilinderformaten. Stuur je gewenste merk en variant of vraag ons het product te bevestigen vóór een bezorgofferte.',
 'Vous choisissez des cartouches pour votre cuisine à Al Barsha ? Comparez votre consommation prévue aux formats disponibles. Envoyez la marque et le modèle souhaités ou demandez une confirmation du produit avant un devis de livraison.'),
('deira','Deira',
 'For businesses in Deira comparing a small order with a larger supply, send a list of products and quantities. We can discuss cream charger tanks as well as Smartwhip and Cream Deluxe cylinders, with current pricing confirmed in your quote.',
 'Voor bedrijven in Deira die een kleine bestelling vergelijken met een grotere voorraad: stuur een lijst met producten en aantallen. We bespreken lachgastanks en Smartwhip- en Cream Deluxe-cilinders, met de actuele prijzen in je offerte.',
 'Pour les entreprises de Deira comparant une petite commande à un approvisionnement plus important, envoyez les produits et quantités. Nous discutons des réservoirs N2O et des cylindres Smartwhip et Cream Deluxe, avec les prix actuels confirmés dans le devis.')]
T={
'en':dict(title='Cream Chargers {area} | N2O & Smartwhip Dubai',desc='Culinary N2O cream chargers in {area}, Dubai. Smartwhip and Cream Deluxe enquiries, WhatsApp orders and cash on delivery.',eyebrow='DUBAI · CULINARY N2O',h1='Cream Chargers & N2O',intro='Explore Smartwhip, Cream Deluxe and culinary nitrous oxide cylinders for your kitchen in {area}. Nitrous oxide is also known as laughing gas or lachgas. Order via WhatsApp and pay cash on delivery.',chat='Order for {area} ↗',section='Cream charger enquiries in {area}',range='Choose your culinary cylinder',p1='Compare the product descriptions and check the exact cylinder size, regulator and fittings with us before ordering. The range is intended for culinary cream whipping with appropriate equipment.',smart='Smartwhip Silver',deluxe='Cream Deluxe Cylinder',tank='Cream Charger Tanks',delivery='Delivery & cash payment in {area}',dp='Send your product, quantity and full address in {area}. We confirm stock, service availability, a delivery window, any delivery fees and your total before dispatch. Pay in cash when your order arrives.',faq='Ordering questions',q1='Can I arrange delivery to {area}?',a1='Send your exact location via WhatsApp. We will confirm availability, delivery timing and charges for your order.',q2='How do I choose a cylinder?',a2='Share your dispenser model and intended culinary usage. Confirm the product size, fittings and compatible equipment before ordering.',q3='Can I request a business quote?',a3='Yes. Send a product list, quantities and your delivery address for current pricing.',near='Explore other Dubai areas',index='Cream chargers across Dubai',message='Hello, I would like to discuss culinary cream chargers for delivery in {area}, Dubai, and pay cash on delivery. Please confirm products, availability, delivery timing, fees and total.'),
'nl':dict(title='Lachgas & Slagroompatronen {area} | Dubai',desc='Culinaire N2O-slagroompatronen in {area}, Dubai. Smartwhip en Cream Deluxe. Bestel via WhatsApp en betaal contant bij bezorging.',eyebrow='DUBAI · CULINAIR N2O',h1='Slagroompatronen & Lachgas',intro='Ontdek Smartwhip, Cream Deluxe en culinaire lachgascilinders voor je keuken in {area}. Lachgas (N2O) heet in het Engels nitrous oxide of laughing gas. Bestel via WhatsApp en betaal contant bij bezorging.',chat='Bestel voor {area} ↗',section='Slagroompatronen aanvragen in {area}',range='Kies je culinaire cilinder',p1='Vergelijk de productomschrijvingen en controleer vóór je bestelling het exacte formaat, de regelaar en aansluitingen met ons. Het assortiment is bedoeld voor culinair gebruik met geschikte apparatuur.',smart='Smartwhip Silver',deluxe='Cream Deluxe-cilinder',tank='Lachgastanks voor slagroom',delivery='Bezorging en contante betaling in {area}',dp='Stuur je product, aantal en volledige adres in {area}. We bevestigen vóór verzending de voorraad, bezorgmogelijkheden, bezorgtijd, eventuele bezorgkosten en het totaal. Betaal contant wanneer je bestelling aankomt.',faq='Vragen over bestellen',q1='Kan ik bezorging naar {area} regelen?',a1='Stuur je exacte locatie via WhatsApp. We bevestigen beschikbaarheid, bezorgtijd en kosten voor jouw bestelling.',q2='Hoe kies ik een cilinder?',a2='Deel het model van je slagroomspuit en het beoogde culinaire gebruik. Controleer vóór je bestelling het formaat, de aansluitingen en passende apparatuur.',q3='Kan ik een zakelijke offerte aanvragen?',a3='Ja. Stuur een productlijst, aantallen en je bezorgadres voor actuele prijzen.',near='Bekijk andere gebieden in Dubai',index='Slagroompatronen in Dubai',message='Hallo, ik wil culinaire slagroompatronen bespreken voor bezorging in {area}, Dubai, en contant betalen bij bezorging. Graag producten, voorraad, bezorgtijd, kosten en totaal bevestigen.'),
'fr':dict(title='Cartouches de crème & N2O {area} | Dubaï',desc='Cartouches de crème au N2O à usage culinaire à {area}, Dubaï. Smartwhip et Cream Deluxe. Commande WhatsApp et espèces à la livraison.',eyebrow='DUBAÏ · N2O CULINAIRE',h1='Cartouches de crème & N2O',intro='Découvrez Smartwhip, Cream Deluxe et les cylindres de protoxyde d’azote pour votre cuisine à {area}. Le N2O est aussi appelé gaz hilarant ou lachgas en néerlandais. Commandez sur WhatsApp et payez en espèces à la livraison.',chat='Commander pour {area} ↗',section='Demander des cartouches de crème à {area}',range='Choisissez votre cylindre culinaire',p1='Comparez les descriptions et vérifiez avec nous la taille exacte, le régulateur et les raccords avant de commander. La gamme est destinée à la préparation culinaire avec un équipement adapté.',smart='Smartwhip Silver',deluxe='Cylindre Cream Deluxe',tank='Réservoirs N2O pour crème',delivery='Livraison et paiement en espèces à {area}',dp='Envoyez le produit, la quantité et l’adresse complète à {area}. Nous confirmons le stock, la disponibilité du service, le créneau, les frais éventuels et le montant total avant l’expédition. Payez en espèces à la réception.',faq='Questions sur les commandes',q1='Puis-je organiser une livraison à {area} ?',a1='Envoyez votre localisation exacte sur WhatsApp. Nous confirmerons la disponibilité, le délai et les frais pour votre commande.',q2='Comment choisir un cylindre ?',a2='Indiquez le modèle de votre siphon et l’usage culinaire prévu. Confirmez la taille, les raccords et le matériel compatible avant de commander.',q3='Puis-je demander un devis professionnel ?',a3='Oui. Envoyez les produits, les quantités et l’adresse de livraison pour connaître les prix actuels.',near='Découvrir d’autres quartiers de Dubaï',index='Cartouches de crème à Dubaï',message='Bonjour, je souhaite discuter de cartouches de crème à usage culinaire pour une livraison à {area}, Dubaï, avec paiement en espèces. Merci de confirmer les produits, le stock, le délai, les frais et le total.')}
def route(lang,slug=''):return ('/'+lang if lang!='en' else '')+'/'+slug
from html import escape
for lang in ['en','nl','fr']:
 base=(root/(lang if lang!='en' else '')/'index.html').read_text()
 prefix=base.split('<main>')[0];footer=base[base.index('<footer'):]
 links=''.join(f'<a href="{route(lang,"cream-chargers-"+slug+"/")}">{name} →</a>' for slug,name,*_ in areas)
 block=f'<section class="section" id="delivery-areas"><span class="eyebrow">DUBAI</span><h2>{T[lang]["index"]}</h2><div class="area-links">{links}</div></section>'
 base=re.sub(r'<!-- AREAS START -->.*?<!-- AREAS END -->','',base,flags=re.S)
 base=base.replace('</main>','<!-- AREAS START -->'+block+'<!-- AREAS END --></main>');(root/(lang if lang!='en' else '')/'index.html').write_text(base)
 for slug,area,*paras in areas:
  path='cream-chargers-'+slug+'/';v={k:x.format(area=area) for k,x in T[lang].items()};para=paras[['en','nl','fr'].index(lang)]
  header=re.sub(r'<title>.*?</title>','<title>'+escape(v['title'])+'</title>',prefix)
  header=re.sub(r'(<meta name="description" content=")[^"]*',r'\g<1>'+escape(v['desc'],quote=True),header)
  header=re.sub(r'(<meta property="og:title" content=")[^"]*',r'\g<1>'+escape(v['title'],quote=True),header)
  header=re.sub(r'(<meta property="og:description" content=")[^"]*',r'\g<1>'+escape(v['desc'],quote=True),header)
  header=re.sub(r'<link rel="(?:alternate|canonical)"[^>]*>','',header)
  tags=''.join(f'<link rel="alternate" hreflang="{l}" href="{origin}{route(l,path)}">' for l in ['en','nl','fr'])+f'<link rel="canonical" href="{origin}{route(lang,path)}">'
  header=header.replace('</head>',tags+'</head>')
  for l in ['en','nl','fr']:header=header.replace(f'href="{route(l)}" lang="{l}"',f'href="{route(l,path)}" lang="{l}"')
  wa='https://wa.me/31684227916?text='+quote(v['message'])
  body=f'<main><section class="hero area-hero"><div class="hero-content"><div><span class="eyebrow">{v["eyebrow"]}</span><h1>{v["h1"]}<br><em>{area}</em></h1><p>{v["intro"]}</p><div class="actions"><a class="btn" href="{wa}">{v["chat"]}</a></div></div></div></section><section class="section split"><div><span class="eyebrow">{area.upper()}</span><h2>{v["section"]}</h2><p>{para}</p></div><div><h2>{v["range"]}</h2><p>{v["p1"]}</p><div class="area-links">'
  for key,product in [('smart','smartwhip-silver'),('deluxe','cream-deluxe-cylinder'),('tank','cream-charger-tanks')]:body+=f'<a href="{route(lang,product+"/")}">{v[key]} →</a>'
  body+=f'</div></div></section><section class="wide"><div class="section"><h2>{v["delivery"]}</h2><p>{v["dp"]}</p><a class="btn" href="{wa}">{v["chat"]}</a></div></section><section class="section faq"><h2>{v["faq"]}</h2>'
  for i in range(1,4):body+=f'<details><summary>{v["q"+str(i)]}</summary><p>{v["a"+str(i)]}</p></details>'
  body+=f'</section><section class="section"><h2>{v["near"]}</h2><div class="area-links">{links}</div></section></main>'
  dest=root/route(lang,path).lstrip('/');dest.mkdir(parents=True,exist_ok=True);(dest/'index.html').write_text(header+body+footer)
css=root/'style.css';s=css.read_text();extra='.area-links{display:flex;flex-wrap:wrap;gap:12px}.area-links a{padding:11px 16px;border:1px solid #d6b65a55;border-radius:5px;color:#e9c361;background:#0b233d;font-size:14px}.area-hero{min-height:530px}.area-hero h1{font-size:clamp(38px,4.5vw,65px)}.area-hero p{max-width:520px}@media(max-width:800px){.area-hero{min-height:620px}.area-hero h1{font-size:44px}}'
if extra not in s:css.write_text(s+'\n'+extra)
urls=[]
for p in root.rglob('index.html'):
 r=p.relative_to(root).parent;urls.append(origin+'/'+('' if str(r)=='.' else str(r)+'/'))
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in sorted(urls))+'</urlset>')
print('Created 24 localized landing pages for 8 Dubai areas; homepage links and sitemap updated.')
