from pathlib import Path
from html import escape as e
from urllib.parse import quote
import re,json
root=Path(__file__).parent/'dist'
origin='https://creamchargersdubai.com'
slug='blog/dubai-delivery-24-7-cream-deluxe-offer/'
data={
'en':('Fast Cream Deluxe Delivery Across Dubai — Available 24/7','Based in Dubai, available 24/7 and delivering quickly across the city. Order 3 Cream Deluxe cylinders for AED 1,500 via WhatsApp.', 'I live in Dubai and supply Cream Deluxe cylinders across Dubai. Whether you are stocking a café, restaurant or your own kitchen, you can contact me any time, day or night, to arrange your order.', [('Local service throughout Dubai','Being based in Dubai means you can order directly from a local supplier. I deliver throughout Dubai, including Dubai Marina, Downtown Dubai, Business Bay, JBR, Jumeirah, Palm Jumeirah, Al Barsha and Deira. Send your exact address on WhatsApp to arrange delivery.'),('Available 24/7 with fast delivery','I am available 24 hours a day, 7 days a week. Message me whenever you need to order or ask about stock. I offer fast delivery across Dubai; send your location and I will confirm the expected delivery time before dispatch.'),('Special offer: 3 cylinders for AED 1,500','Order 3 Cream Deluxe cylinders together for AED 1,500 — AED 500 per cylinder. The regular single-cylinder price is AED 600, so you save AED 300 compared with buying three separately. This offer applies to Cream Deluxe cylinders.'),('Order directly through WhatsApp','Send a message requesting the 3-cylinder offer and include your delivery address. I will confirm stock, delivery timing, any delivery charge and the final total. Pay cash on delivery. Cream Deluxe cylinders are intended for culinary cream whipping and foams with compatible equipment.')], 'Order 3 for AED 1,500 ↗','Hello, I would like 3 Cream Deluxe cylinders for AED 1,500. My Dubai delivery address is: . Please confirm availability, delivery time, any delivery charge and the final total.','Read the blog →'),
'nl':('Snelle Cream Deluxe-bezorging in heel Dubai — 24/7 bereikbaar','Ik woon in Dubai, ben 24/7 bereikbaar en lever snel door heel Dubai. Bestel 3 Cream Deluxe-cilinders voor AED 1.500 via WhatsApp.','Ik woon in Dubai en lever Cream Deluxe-cilinders door heel Dubai. Voor je café, restaurant of eigen keuken kun je rechtstreeks bij mij bestellen. Je kunt mij dag en nacht bereiken om je bestelling te regelen.',[('Lokale levering door heel Dubai','Omdat ik in Dubai woon, bestel je rechtstreeks bij een lokale leverancier. Ik lever door heel Dubai, onder andere in Dubai Marina, Downtown Dubai, Business Bay, JBR, Jumeirah, Palm Jumeirah, Al Barsha en Deira. Stuur je exacte adres via WhatsApp om de bezorging af te spreken.'),('24/7 bereikbaar en snelle bezorging','Ik ben 24 uur per dag, 7 dagen per week bereikbaar. Stuur gerust een bericht wanneer je wilt bestellen of de voorraad wilt controleren. Ik lever snel door heel Dubai. Stuur je locatie en ik bevestig vóór vertrek de verwachte bezorgtijd.'),('Aanbieding: 3 cilinders voor AED 1.500','Neem 3 Cream Deluxe-cilinders tegelijk voor AED 1.500: dat is AED 500 per cilinder. De normale prijs voor één cilinder is AED 600. Je bespaart dus AED 300 ten opzichte van drie losse cilinders. Deze aanbieding geldt voor Cream Deluxe-cilinders.'),('Bestel rechtstreeks via WhatsApp','Stuur dat je de aanbieding van 3 cilinders wilt en vermeld je bezorgadres. Ik bevestig de voorraad, bezorgtijd, eventuele bezorgkosten en het totaalbedrag. Je betaalt contant bij bezorging. Cream Deluxe-cilinders zijn bedoeld voor culinaire slagroom en schuim met geschikte apparatuur.')], 'Bestel 3 voor AED 1.500 ↗','Hallo, ik wil 3 Cream Deluxe-cilinders voor AED 1.500 bestellen. Mijn bezorgadres in Dubai is: . Graag voorraad, bezorgtijd, eventuele bezorgkosten en totaal bevestigen.','Lees de blog →'),
'fr':('Livraison rapide de Cream Deluxe dans tout Dubaï — Disponible 24 h/24','Je vis à Dubaï, suis disponible 24 h/24 et 7 j/7 et livre rapidement dans toute la ville. Commandez 3 cylindres Cream Deluxe pour 1 500 AED.','Je vis à Dubaï et livre des cylindres Cream Deluxe dans toute la ville. Pour votre café, restaurant ou cuisine, vous pouvez commander directement auprès de moi et me contacter à toute heure, de jour comme de nuit.',[('Un fournisseur local dans tout Dubaï','Installé à Dubaï, je livre dans toute la ville, notamment à Dubai Marina, Downtown Dubai, Business Bay, JBR, Jumeirah, Palm Jumeirah, Al Barsha et Deira. Envoyez votre adresse exacte sur WhatsApp pour organiser la livraison.'),('Disponible 24 h/24 et 7 j/7, avec une livraison rapide','Vous pouvez me contacter 24 heures sur 24, 7 jours sur 7, pour commander ou vérifier le stock. Je propose une livraison rapide dans tout Dubaï. Envoyez votre localisation et je confirmerai le délai prévu avant le départ.'),('Offre spéciale : 3 cylindres pour 1 500 AED','Commandez 3 cylindres Cream Deluxe ensemble pour 1 500 AED, soit 500 AED par cylindre. Le prix habituel d’un cylindre est de 600 AED : vous économisez donc 300 AED par rapport à trois achats séparés. Cette offre concerne les cylindres Cream Deluxe.'),('Commandez directement sur WhatsApp','Demandez l’offre de 3 cylindres et indiquez votre adresse de livraison. Je confirmerai le stock, le délai, les éventuels frais de livraison et le montant total. Payez en espèces à la livraison. Les cylindres Cream Deluxe sont destinés à la crème fouettée et aux mousses culinaires avec un équipement compatible.')], 'Commander 3 pour 1 500 AED ↗','Bonjour, je souhaite commander 3 cylindres Cream Deluxe pour 1 500 AED. Mon adresse à Dubaï est : . Merci de confirmer le stock, le délai, les éventuels frais de livraison et le total.','Lire l’article →')}
def route(l,p):return ('/'+l if l!='en' else '')+'/'+p
for l,(title,desc,lead,sections,button,message,read) in data.items():
 base=(root/route(l,'blog/cream-charger-delivery-dubai/').lstrip('/')/'index.html').read_text()
 prefix=base.split('<main>')[0];footer=base[base.index('<footer'):]
 prefix=re.sub(r'<title>.*?</title>', '<title>'+e(title)+'</title>',prefix)
 prefix=re.sub(r'<script type="application/ld\+json">.*?</script>','',prefix)
 prefix=re.sub(r'<link rel="(?:canonical|alternate)"[^>]*>','',prefix)
 for prop,val in [('name="description"',desc),('property="og:title"',title),('property="og:description"',desc)]:prefix=re.sub('(<meta '+prop+' content=")[^"]*',lambda m:m[1]+e(val,quote=True),prefix)
 for lang in data:prefix=prefix.replace(route(lang,'blog/cream-charger-delivery-dubai/'),route(lang,slug))
 tags=''.join(f'<link rel="alternate" hreflang="{lang}" href="{origin}{route(lang,slug)}">' for lang in data)+f'<link rel="canonical" href="{origin}{route(l,slug)}">'
 schema={'@context':'https://schema.org','@type':'BlogPosting','headline':title,'description':desc,'datePublished':'2026-10-09T15:15:00+04:00','dateModified':'2026-10-09T15:15:00+04:00','inLanguage':l,'author':{'@type':'Organization','name':'Smartwhip Dubai'},'image':origin+'/assets/hero.webp','mainEntityOfPage':origin+route(l,slug)}
 prefix=prefix.replace('</head>',tags+'<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script></head>')
 body='<main><article class="article blog-article"><div class="eyebrow">BLOG · 09 / 10 / 2026</div><h1>'+e(title)+'</h1><p class="blog-lead">'+e(lead)+'</p><img class="poster blog-image" src="/assets/hero.webp" alt="Cream Deluxe · Dubai"><div class="contact"><div><h2>3 × Cream Deluxe</h2><p class="gold">AED 1,500 · AED 500 / '+('cylinder' if l=='en' else 'cilinder' if l=='nl' else 'cylindre')+'</p></div></div>'
 for h,p in sections:body+='<h2>'+e(h)+'</h2><p>'+e(p)+'</p>'
 body+=f'<div class="actions"><a class="btn" href="https://wa.me/31684227916?text={quote(message)}">{e(button)}</a><a class="btn outline" href="{route(l,"cream-deluxe-cylinder/")}">Cream Deluxe →</a></div></article></main>'
 dest=root/route(l,slug).lstrip('/');dest.mkdir(parents=True,exist_ok=True);(dest/'index.html').write_text(prefix+body+footer)
 card=f'<article class="blog-card"><img src="/assets/hero.webp" alt="Cream Deluxe · Dubai" loading="lazy"><div><span class="eyebrow">09 / 10 / 2026 · 24/7</span><h2>{e(title)}</h2><p>{e(desc)}</p><a class="btn outline" href="{route(l,slug)}">{e(read)}</a></div></article>'
 for path in ['blog/','']:
  f=root/route(l,path).lstrip('/')/'index.html';s=f.read_text()
  if route(l,slug) not in s:
   if path:s=s.replace('<article class="blog-card">',card+'<article class="blog-card">',1)
   else:s=s.replace('<!-- BLOG START -->','<!-- BLOG START -->'+f'<section class="section">{card}</section>')
   f.write_text(s)
urls=[origin+'/'+('' if str(p.relative_to(root).parent)=='.' else str(p.relative_to(root).parent)+'/') for p in root.rglob('index.html')]
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in sorted(urls))+'</urlset>')
print('Added Dubai 24/7 offer blog in EN/NL/FR, index and homepage links, SEO and sitemap.')
